name: Gatsby GitHub Stats Screenshot
on:
  schedule:
    - cron: "10 * * * *"
jobs:
  run_puppeteer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Screenshot
        uses: "lannonbr/puppeteer-screenshot-action@1.0.1"
        with:
          url: https://gatsby-github-stats.netlify.com
      - name: Push to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_URL: ${{ secrets.BUCKET_URL }}
        run: aws s3 cp $GITHUB_WORKSPACE/screenshots/ $BUCKET_URL --recursive
